### ISSUE TITLE
Doesn't appear to be working

### ISSUE THREAD

**Issue by ThePiercedPrince** [starfi5h/DSP_Mod_Support#1]
I installed this fixer w/personal logistics by Semar and Longarm and neither seem to be functioning.  Not sure what I am doing wrong, or if there is something else interfering.  I tested in a new game with just longarm and PL.

**Comment by starfi5h** [comment]
Solved. Conversation: https://discord.com/channels/806549677209944084/806935746098495584/1034166776021385226.
Summary:
1. Check `BepInEx\LogOutput.log` to see if mods are working normally.  
2. Clear mod cache in mod managers and reinstall the mods.
