### ISSUE TITLE
[FactoryLocator] missing warning 

### ISSUE THREAD

**Issue by cyan** [starfi5h/DSP_Mod_Support#12]
Hi, 
since a few days ago the warning for "not enough material in factory" won't show up un factorylocator
i m not sure if it's related but at some point i disabled the warning itself in the game settings to do some tests and enabled it after few minutes (seems like around the same time the error appeared)
i tried to do the same with the other errors shown on the screenshot but they are still working fine

![image](https://github.com/starfi5h/DSP_Mod_Support/assets/90098/c918e59a-e52f-46e0-bddd-33f86b72426f)

**Comment by starfi5h** [comment]
This warning is created from the mod BetterWarningIcons.
This mod is not compatible with BetterWarningIcons.

**Comment by starfi5h** [comment]
BetterWarningIcons compat has been added in FactoryLocator v1.2.2

**Comment by cyan** [comment]
oh, didn t realised that one, thanks for clarifying this
