### ISSUE TITLE
[FactoryLocator] [enhancement] filtering factories

### ISSUE THREAD

**Issue by cyan** [starfi5h/DSP_Mod_Support#13]
It would be nice to be able to filter those liquid extractors for when we use the "Low on ressource" warning.
as i use it mainly to find miner soon to be out of work, a lot of water/oil extractor show up and it become a complet mess on the screen (as the liquid extractors are always low on ressources)

**Comment by starfi5h** [comment]
Now you can right click on query results to remove the group.
But I suggest you to inform the author BetterWarningIcons not add "Low on resource" on liquid extractors.

**Comment by cyan** [comment]
wow, just tried it and it s a great work around :)
thanks a lot
