### ISSUE TITLE
BUG, Could not find file \starfi5h.plugin.MassRecipePaste.cfg"

### ISSUE THREAD

**Issue by sherlockHlb** [starfi5h/DSP_Mod_Support#14]
[Error  : Unity Log] FileNotFoundException: Could not find file "G:\SteamLibrary\steamapps\common\Dyson Sphere Program\BepInEx\config\starfi5h.plugin.MassRecipePaste.cfg"
Stack trace:
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <2fa7a6a452ca43df998f07fd1486c0df>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) (at <2fa7a6a452ca43df998f07fd1486c0df>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize, System.Boolean checkHost) (at <2fa7a6a452ca43df998f07fd1486c0df>:0)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) (at <2fa7a6a452ca43df998f07fd1486c0df>:0)
System.IO.StreamReader..ctor (System.String path, System.Boolean detectEncodingFromByteOrderMarks) (at <2fa7a6a452ca43df998f07fd1486c0df>:0)
System.IO.StreamReader..ctor (System.String path) (at <2fa7a6a452ca43df998f07fd1486c0df>:0)
(wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(string)
System.IO.File.OpenText (System.String path) (at <2fa7a6a452ca43df998f07fd1486c0df>:0)
System.IO.File.ReadAllLines (System.String path) (at <2fa7a6a452ca43df998f07fd1486c0df>:0)
BepInEx.Configuration.ConfigFile.Reload () (at <23c82cada6174aeea1f2659206cab34d>:0)
MassRecipePaste.ExtraCopy.OnApplyClick () (at <ef3bffa7a211424ca6e9c05780a7b03d>:0)
UIOptionWindow.OnApplyClick (System.Int32 obj) (at <b5b97811177147feb5a75cac33a23e4b>:0)
UIButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <b5b97811177147feb5a75cac33a23e4b>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <32bd6c8a2dd3414ca080d595da90bbab>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <32bd6c8a2dd3414ca080d595da90bbab>:0)
UnityEngine.EventSystems.EventSystem:Update()

是不是忘记写了生成config,我在文件内也没有找到这个配置文件.

Did you forget to write the generated config? I didn't find this configuration file in the file.

**Comment by starfi5h** [comment]
在mod载入时就应该会生成config了
我这里的写法和DeliverySlotsTweaks是一样的
你可以测试DeliverySlotsTweaks是否有相同的错误

**Comment by sherlockHlb** [comment]
![image](https://github.com/user-attachments/assets/a021254a-e3ea-4ccf-8380-c8d5d204f347)
有DeliverySlotsTweaks的cfg,但是没有MassRecipePaste的

**Comment by sherlockHlb** [comment]
[Info   :   BepInEx] Loading [MassRecipePaste 1.1.0]
[Error  : Unity Log] ArgumentException: Type BepInEx.Configuration.KeyboardShortcut is not supported by the config system. Supported types: String, Boolean, Byte, SByte, Int16, UInt16, Int32, UInt32, Int64, UInt64, Single, Double, Decimal, Enum, Color, Vector2, Vector3, Vector4, Quaternion
Stack trace:
BepInEx.Configuration.ConfigFile.Bind[T] (BepInEx.Configuration.ConfigDefinition configDefinition, T defaultValue, BepInEx.Configuration.ConfigDescription configDescription) (at <23c82cada6174aeea1f2659206cab34d>:0)
BepInEx.Configuration.ConfigFile.Bind[T] (System.String section, System.String key, T defaultValue, System.String description) (at <23c82cada6174aeea1f2659206cab34d>:0)
MassRecipePaste.Plugin.LoadConfigs () (at <ef3bffa7a211424ca6e9c05780a7b03d>:0)
MassRecipePaste.Plugin.Awake () (at <ef3bffa7a211424ca6e9c05780a7b03d>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
XLogHandler:Register()
GlobalObject:Initialize()

**Comment by starfi5h** [comment]
你用的BepInEx版本是thunderstore上的5.4.17? 还是其他地方的版本?

正常的log会是这样子 [LogOutput.log](https://github.com/user-attachments/files/16318930/LogOutput.log)

**Comment by sherlockHlb** [comment]
[Message:   BepInEx] BepInEx 5.4.17.0 - DSPGAME (2021/1/31 11:59:19)
[Info   :   BepInEx] Running under Unity v2018.4.12.5889476
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started

**Comment by starfi5h** [comment]
试试这个移除自定义热键的版本
你可以用Import local mod的方式导入
[MassRecipePaste.zip](https://github.com/user-attachments/files/16319054/MassRecipePaste.zip)

**Comment by sherlockHlb** [comment]
可以修改热键,修改完毕后也生效,但是修改的时候会弹bug窗体,也没有发现cfg文件，就很离谱。

**Comment by starfi5h** [comment]
[MassRecipePaste.zip](https://github.com/user-attachments/files/16322175/MassRecipePaste.zip)
这个再不行我也就没办法了
