### ISSUE TITLE
这个还更新吗？能不能加入DspGameSpeed的适配？这个好用

### ISSUE THREAD

**Issue by Terrevil** [starfi5h/DSP_Mod_Support#16]
这个mod 的速度调控比 隔壁 auxilaryfunction 的更丝滑，占用资源更小

3年前的mod好用一直用到昨天的更新
https://thunderstore.io/c/dyson-sphere-program/p/dsp-mods/DspGameSpeed/

**Comment by starfi5h** [comment]
似乎是UI元件位置改变导致出错
等我其他mod更新完后会尝试修复

**Comment by Terrevil** [comment]
坐等。

**Comment by starfi5h** [comment]
先试试看本地版本, 可以用手动安装或r2->Settings->Probifle分页->Import local mod导入zip
[DSP-game-speed(0.8.0).zip](https://github.com/user-attachments/files/16651888/DSP-game-speed.0.8.0.zip)
要注意一下帧率平衡(shift+f12)要调整才可以让3倍速生效, 不然UPS会被FPS限制
因为上述帧率平衡的缘故, 我不确定自定义帧率这个设置还有没有意义

看mod的反馈说ctrl+0~3的热键和建筑栏位冲突所以我先拿掉了
有什么建议可以提出

**Comment by starfi5h** [comment]
已将游戏倍速调整功能整合进BulletTime v1.5.0
https://thunderstore.io/c/dyson-sphere-program/p/starfi5h/BulletTime/
