### ISSUE TITLE
Suggestion: Fork LongArm

### ISSUE THREAD

**Issue by shayded-exe** [starfi5h/DSP_Mod_Support#5]
LongArm hasn't been updated in over a year. Why not just fork it instead of having a separate patch mod?

**Comment by starfi5h** [comment]
ModFixerOne can fix the other 3 mods with the same method (adding missing fields/methods).

The reason I don't fork LongArm is:
1. Its implementation conflicts with NebulaMultiplayerMod.
2. Most of its features can be found in other mods. For example:

Open far buildings from map view => [ExpandTouchableRange](https://dsp.thunderstore.io/package/hetima/ExpandTouchableRange/)
Extend construction range =>[MechaDronesTweaks](https://dsp.thunderstore.io/package/soarqin/MechaDronesTweaks/)
Locate parts of the planet/factory => [FactoryLocator](https://dsp.thunderstore.io/package/starfi5h/FactoryLocator/)  

`FlyToBuild` => `Auto fly to unfinished buildings` in [Auxilaryfunction](https://dsp.thunderstore.io/package/blacksnipebiu/Auxilaryfunction/)
![aux206](https://github.com/starfi5h/DSP_Mod_Support/assets/50672801/1ed6ec73-b6d5-40dc-8215-77d13cfa6253)

`FastBuild` => `Constructions complete in seconds` in [Multfuntion_mod](https://dsp.thunderstore.io/package/blacksnipebiu/Multfuntion_mod/)
`FreeBuild` => `ArchitectMode` in [Multfuntion_mod](https://dsp.thunderstore.io/package/blacksnipebiu/Multfuntion_mod/)
![op-building](https://github.com/starfi5h/DSP_Mod_Support/assets/50672801/70d3c57a-7258-4477-9bb0-1f8510973061)
