### ISSUE TITLE
long arm模组用增产剂喷蓄电器会报错 并且 建造距离会在(每一次)进入存档的时候重置成80 (原本是600)

### ISSUE THREAD

**Issue by newbienoobplayer** [starfi5h/DSP_Mod_Support#7]
![Screenshot (610)](https://github.com/starfi5h/DSP_Mod_Support/assets/138718840/31fdab6a-0b21-4366-b7d3-86c1b40108a2)

我已经安装了 ModFixerOne,麻烦大佬了

**Comment by starfi5h** [comment]
我不打算继续维护LongArm了, 请改用其他的mod
你可以看看soarqin的mod, 像是MechaDronesTweaks或CheatEnabler

**Comment by newbienoobplayer** [comment]
请问能推荐一个有着类型喷涂功能的mod吗?
